// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace lcts {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class LogInfoCsharp {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static LogInfoCsharp() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpsY3RzL2xvZ19pbmZvX2NzaGFycC5wcm90bxIEbGN0cxoTbGN0cy9sb2df", 
          "aW5mby5wcm90bw=="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::Proto.LogInfo.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
}

#endregion Designer generated code
