#ifndef _CTP_CMESSAGE_
#define _CTP_CMESSAGE_

//CTP CMessageDef

enum {
	MD_ONFRONTCONNECTED = 3000,

	MD_ONFRONTDISCONNECTED,

	MD_ONHEARTBEATWARNING,

	MD_ONRSPUSERLOGIN,

	MD_ONRSPUSERLOGOUT,

	MD_ONRSPERROR,

	MD_ONRSPSUBMARKETDATA,

	MD_ONRSPUNSUBMARKETDATA,

	MD_ONRSPSUBFORQUOTERSP,

	MD_ONRSPUNSUBFORQUOTERSP,

	MD_ONRTNDEPTHMARKETDATA,

	MD_ONRTNFORQUOTERSP,

	TRADER_ONFRONTCONNECTED,

	TRADER_ONFRONTDISCONNECTED,

	TRADER_ONHEARTBEATWARNING,

	TRADER_ONRSPAUTHENTICATE,

	TRADER_ONRSPUSERLOGIN,

	TRADER_ONRSPUSERLOGOUT,

	TRADER_ONRSPUSERPASSWORDUPDATE,

	TRADER_ONRSPTRADINGACCOUNTPASSWORDUPDATE,

	TRADER_ONRSPORDERINSERT,

	TRADER_ONRSPPARKEDORDERINSERT,

	TRADER_ONRSPPARKEDORDERACTION,

	TRADER_ONRSPORDERACTION,

	TRADER_ONRSPQUERYMAXORDERVOLUME,

	TRADER_ONRSPSETTLEMENTINFOCONFIRM,

	TRADER_ONRSPREMOVEPARKEDORDER,

	TRADER_ONRSPREMOVEPARKEDORDERACTION,

	TRADER_ONRSPEXECORDERINSERT,

	TRADER_ONRSPEXECORDERACTION,

	TRADER_ONRSPFORQUOTEINSERT,

	TRADER_ONRSPQUOTEINSERT,

	TRADER_ONRSPQUOTEACTION,

	TRADER_ONRSPQRYORDER,

	TRADER_ONRSPQRYTRADE,

	TRADER_ONRSPQRYINVESTORPOSITION,

	TRADER_ONRSPQRYTRADINGACCOUNT,

	TRADER_ONRSPQRYINVESTOR,

	TRADER_ONRSPQRYTRADINGCODE,

	TRADER_ONRSPQRYINSTRUMENTMARGINRATE,

	TRADER_ONRSPQRYINSTRUMENTCOMMISSIONRATE,

	TRADER_ONRSPQRYEXCHANGE,

	TRADER_ONRSPQRYPRODUCT,

	TRADER_ONRSPQRYINSTRUMENT,

	TRADER_ONRSPQRYDEPTHMARKETDATA,

	TRADER_ONRSPQRYSETTLEMENTINFO,

	TRADER_ONRSPQRYTRANSFERBANK,

	TRADER_ONRSPQRYINVESTORPOSITIONDETAIL,

	TRADER_ONRSPQRYNOTICE,

	TRADER_ONRSPQRYSETTLEMENTINFOCONFIRM,

	TRADER_ONRSPQRYINVESTORPOSITIONCOMBINEDETAIL,

	TRADER_ONRSPQRYCFMMCTRADINGACCOUNTKEY,

	TRADER_ONRSPQRYEWARRANTOFFSET,

	TRADER_ONRSPQRYINVESTORPRODUCTGROUPMARGIN,

	TRADER_ONRSPQRYEXCHANGEMARGINRATE,

	TRADER_ONRSPQRYEXCHANGEMARGINRATEADJUST,

	TRADER_ONRSPQRYEXCHANGERATE,

	TRADER_ONRSPQRYSECAGENTACIDMAP,

	TRADER_ONRSPQRYOPTIONINSTRTRADECOST,

	TRADER_ONRSPQRYOPTIONINSTRCOMMRATE,

	TRADER_ONRSPQRYEXECORDER,

	TRADER_ONRSPQRYFORQUOTE,

	TRADER_ONRSPQRYQUOTE,

	TRADER_ONRSPQRYTRANSFERSERIAL,

	TRADER_ONRSPQRYACCOUNTREGISTER,

	TRADER_ONRSPERROR,

	TRADER_ONRTNORDER,

	TRADER_ONRTNTRADE,

	TRADER_ONERRRTNORDERINSERT,

	TRADER_ONERRRTNORDERACTION,

	TRADER_ONRTNINSTRUMENTSTATUS,

	TRADER_ONRTNTRADINGNOTICE,

	TRADER_ONRTNERRORCONDITIONALORDER,

	TRADER_ONRTNEXECORDER,

	TRADER_ONERRRTNEXECORDERINSERT,

	TRADER_ONERRRTNEXECORDERACTION,

	TRADER_ONERRRTNFORQUOTEINSERT,

	TRADER_ONRTNQUOTE,

	TRADER_ONERRRTNQUOTEINSERT,

	TRADER_ONERRRTNQUOTEACTION,

	TRADER_ONRTNFORQUOTERSP,

	TRADER_ONRSPQRYCONTRACTBANK,

	TRADER_ONRSPQRYPARKEDORDER,

	TRADER_ONRSPQRYPARKEDORDERACTION,

	TRADER_ONRSPQRYTRADINGNOTICE,

	TRADER_ONRSPQRYBROKERTRADINGPARAMS,

	TRADER_ONRSPQRYBROKERTRADINGALGOS,

	TRADER_ONRTNFROMBANKTOFUTUREBYBANK,

	TRADER_ONRTNFROMFUTURETOBANKBYBANK,

	TRADER_ONRTNREPEALFROMBANKTOFUTUREBYBANK,

	TRADER_ONRTNREPEALFROMFUTURETOBANKBYBANK,

	TRADER_ONRTNFROMBANKTOFUTUREBYFUTURE,

	TRADER_ONRTNFROMFUTURETOBANKBYFUTURE,

	TRADER_ONRTNREPEALFROMBANKTOFUTUREBYFUTUREMANUAL,

	TRADER_ONRTNREPEALFROMFUTURETOBANKBYFUTUREMANUAL,

	TRADER_ONRTNQUERYBANKBALANCEBYFUTURE,

	TRADER_ONERRRTNBANKTOFUTUREBYFUTURE,

	TRADER_ONERRRTNFUTURETOBANKBYFUTURE,

	TRADER_ONERRRTNREPEALBANKTOFUTUREBYFUTUREMANUAL,

	TRADER_ONERRRTNREPEALFUTURETOBANKBYFUTUREMANUAL,

	TRADER_ONERRRTNQUERYBANKBALANCEBYFUTURE,

	TRADER_ONRTNREPEALFROMBANKTOFUTUREBYFUTURE,

	TRADER_ONRTNREPEALFROMFUTURETOBANKBYFUTURE,

	TRADER_ONRSPFROMBANKTOFUTUREBYFUTURE,

	TRADER_ONRSPFROMFUTURETOBANKBYFUTURE,

	TRADER_ONRSPQUERYBANKACCOUNTMONEYBYFUTURE,

	TRADER_ONRTNOPENACCOUNTBYBANK,

	TRADER_ONRTNCANCELACCOUNTBYBANK,

	TRADER_ONRTNCHANGEACCOUNTBYBANK,

};

enum {
	MD_RELEASE = 4000,

	MD_INIT,

	MD_JOIN,

	MD_REGISTERFRONT,

	MD_REGISTERNAMESERVER,

	MD_REGISTERFENSUSERINFO,

	MD_REGISTERSPI,

	MD_SUBSCRIBEMARKETDATA,

	MD_UNSUBSCRIBEMARKETDATA,

	MD_SUBSCRIBEFORQUOTERSP,

	MD_UNSUBSCRIBEFORQUOTERSP,

	MD_REQUSERLOGIN,

	MD_REQUSERLOGOUT,

	TRADER_RELEASE,

	TRADER_INIT,

	TRADER_JOIN,

	TRADER_REGISTERFRONT,

	TRADER_REGISTERNAMESERVER,

	TRADER_REGISTERFENSUSERINFO,

	TRADER_REGISTERSPI,

	TRADER_SUBSCRIBEPRIVATETOPIC,

	TRADER_SUBSCRIBEPUBLICTOPIC,

	TRADER_REQAUTHENTICATE,

	TRADER_REQUSERLOGIN,

	TRADER_REQUSERLOGOUT,

	TRADER_REQUSERPASSWORDUPDATE,

	TRADER_REQTRADINGACCOUNTPASSWORDUPDATE,

	TRADER_REQORDERINSERT,

	TRADER_REQPARKEDORDERINSERT,

	TRADER_REQPARKEDORDERACTION,

	TRADER_REQORDERACTION,

	TRADER_REQQUERYMAXORDERVOLUME,

	TRADER_REQSETTLEMENTINFOCONFIRM,

	TRADER_REQREMOVEPARKEDORDER,

	TRADER_REQREMOVEPARKEDORDERACTION,

	TRADER_REQEXECORDERINSERT,

	TRADER_REQEXECORDERACTION,

	TRADER_REQFORQUOTEINSERT,

	TRADER_REQQUOTEINSERT,

	TRADER_REQQUOTEACTION,

	TRADER_REQQRYORDER,

	TRADER_REQQRYTRADE,

	TRADER_REQQRYINVESTORPOSITION,

	TRADER_REQQRYTRADINGACCOUNT,

	TRADER_REQQRYINVESTOR,

	TRADER_REQQRYTRADINGCODE,

	TRADER_REQQRYINSTRUMENTMARGINRATE,

	TRADER_REQQRYINSTRUMENTCOMMISSIONRATE,

	TRADER_REQQRYEXCHANGE,

	TRADER_REQQRYPRODUCT,

	TRADER_REQQRYINSTRUMENT,

	TRADER_REQQRYDEPTHMARKETDATA,

	TRADER_REQQRYSETTLEMENTINFO,

	TRADER_REQQRYTRANSFERBANK,

	TRADER_REQQRYINVESTORPOSITIONDETAIL,

	TRADER_REQQRYNOTICE,

	TRADER_REQQRYSETTLEMENTINFOCONFIRM,

	TRADER_REQQRYINVESTORPOSITIONCOMBINEDETAIL,

	TRADER_REQQRYCFMMCTRADINGACCOUNTKEY,

	TRADER_REQQRYEWARRANTOFFSET,

	TRADER_REQQRYINVESTORPRODUCTGROUPMARGIN,

	TRADER_REQQRYEXCHANGEMARGINRATE,

	TRADER_REQQRYEXCHANGEMARGINRATEADJUST,

	TRADER_REQQRYEXCHANGERATE,

	TRADER_REQQRYSECAGENTACIDMAP,

	TRADER_REQQRYOPTIONINSTRTRADECOST,

	TRADER_REQQRYOPTIONINSTRCOMMRATE,

	TRADER_REQQRYEXECORDER,

	TRADER_REQQRYFORQUOTE,

	TRADER_REQQRYQUOTE,

	TRADER_REQQRYTRANSFERSERIAL,

	TRADER_REQQRYACCOUNTREGISTER,

	TRADER_REQQRYCONTRACTBANK,

	TRADER_REQQRYPARKEDORDER,

	TRADER_REQQRYPARKEDORDERACTION,

	TRADER_REQQRYTRADINGNOTICE,

	TRADER_REQQRYBROKERTRADINGPARAMS,

	TRADER_REQQRYBROKERTRADINGALGOS,

	TRADER_REQFROMBANKTOFUTUREBYFUTURE,

	TRADER_REQFROMFUTURETOBANKBYFUTURE,

	TRADER_REQQUERYBANKACCOUNTMONEYBYFUTURE,

	MAX_CTP_CMESSAGE
	//Other User New Added Messages...

};

#endif