// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lcts/log_info.proto

#ifndef PROTOBUF_lcts_2flog_5finfo_2eproto__INCLUDED
#define PROTOBUF_lcts_2flog_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lcts_2flog_5finfo_2eproto();
void protobuf_AssignDesc_lcts_2flog_5finfo_2eproto();
void protobuf_ShutdownFile_lcts_2flog_5finfo_2eproto();

class LogInfo;

// ===================================================================

class LogInfo : public ::google::protobuf::Message {
 public:
  LogInfo();
  virtual ~LogInfo();

  LogInfo(const LogInfo& from);

  inline LogInfo& operator=(const LogInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogInfo& default_instance();

  void Swap(LogInfo* other);

  // implements Message ----------------------------------------------

  LogInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogInfo& from);
  void MergeFrom(const LogInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 pri = 1;
  inline bool has_pri() const;
  inline void clear_pri();
  static const int kPriFieldNumber = 1;
  inline ::google::protobuf::int32 pri() const;
  inline void set_pri(::google::protobuf::int32 value);

  // required string log_str = 2;
  inline bool has_log_str() const;
  inline void clear_log_str();
  static const int kLogStrFieldNumber = 2;
  inline const ::std::string& log_str() const;
  inline void set_log_str(const ::std::string& value);
  inline void set_log_str(const char* value);
  inline void set_log_str(const char* value, size_t size);
  inline ::std::string* mutable_log_str();
  inline ::std::string* release_log_str();
  inline void set_allocated_log_str(::std::string* log_str);

  // @@protoc_insertion_point(class_scope:LogInfo)
 private:
  inline void set_has_pri();
  inline void clear_has_pri();
  inline void set_has_log_str();
  inline void clear_has_log_str();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* log_str_;
  ::google::protobuf::int32 pri_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_lcts_2flog_5finfo_2eproto();
  friend void protobuf_AssignDesc_lcts_2flog_5finfo_2eproto();
  friend void protobuf_ShutdownFile_lcts_2flog_5finfo_2eproto();

  void InitAsDefaultInstance();
  static LogInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// LogInfo

// required int32 pri = 1;
inline bool LogInfo::has_pri() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogInfo::set_has_pri() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogInfo::clear_has_pri() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogInfo::clear_pri() {
  pri_ = 0;
  clear_has_pri();
}
inline ::google::protobuf::int32 LogInfo::pri() const {
  return pri_;
}
inline void LogInfo::set_pri(::google::protobuf::int32 value) {
  set_has_pri();
  pri_ = value;
}

// required string log_str = 2;
inline bool LogInfo::has_log_str() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogInfo::set_has_log_str() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogInfo::clear_has_log_str() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogInfo::clear_log_str() {
  if (log_str_ != &::google::protobuf::internal::kEmptyString) {
    log_str_->clear();
  }
  clear_has_log_str();
}
inline const ::std::string& LogInfo::log_str() const {
  return *log_str_;
}
inline void LogInfo::set_log_str(const ::std::string& value) {
  set_has_log_str();
  if (log_str_ == &::google::protobuf::internal::kEmptyString) {
    log_str_ = new ::std::string;
  }
  log_str_->assign(value);
}
inline void LogInfo::set_log_str(const char* value) {
  set_has_log_str();
  if (log_str_ == &::google::protobuf::internal::kEmptyString) {
    log_str_ = new ::std::string;
  }
  log_str_->assign(value);
}
inline void LogInfo::set_log_str(const char* value, size_t size) {
  set_has_log_str();
  if (log_str_ == &::google::protobuf::internal::kEmptyString) {
    log_str_ = new ::std::string;
  }
  log_str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LogInfo::mutable_log_str() {
  set_has_log_str();
  if (log_str_ == &::google::protobuf::internal::kEmptyString) {
    log_str_ = new ::std::string;
  }
  return log_str_;
}
inline ::std::string* LogInfo::release_log_str() {
  clear_has_log_str();
  if (log_str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = log_str_;
    log_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LogInfo::set_allocated_log_str(::std::string* log_str) {
  if (log_str_ != &::google::protobuf::internal::kEmptyString) {
    delete log_str_;
  }
  if (log_str) {
    set_has_log_str();
    log_str_ = log_str;
  } else {
    clear_has_log_str();
    log_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lcts_2flog_5finfo_2eproto__INCLUDED
